//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ZimmetTakipSistemi
{
    using System;
    using System.Collections.Generic;
    
    public partial class Atık
    {
        public int Atık_ıd { get; set; }
        public Nullable<int> Zimmet_ıd { get; set; }
        public Nullable<int> kullanıcı_ıd { get; set; }
        public Nullable<int> urun_ıd { get; set; }
    
        public virtual Kullanıcı Kullanıcı { get; set; }
        public virtual Urunler Urunler { get; set; }
        public virtual Zimmet Zimmet { get; set; }
    }
}
