//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ZimmetTakipSistemi
{
    using System;
    using System.Collections.Generic;
    
    public partial class Kullanıcı
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Kullanıcı()
        {
            this.Atık = new HashSet<Atık>();
            this.Market = new HashSet<Market>();
            this.Zimmet = new HashSet<Zimmet>();
        }
    
        public int Kullanıcı_ıd { get; set; }
        public string Kullanıcıadı { get; set; }
        public string Kullanıcısoyad { get; set; }
        public Nullable<int> Kullanıcısifre { get; set; }
        public Nullable<int> Departman_ıd { get; set; }
        public Nullable<int> Role_ıd { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Atık> Atık { get; set; }
        public virtual Departman Departman { get; set; }
        public virtual Rol Rol { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Market> Market { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Zimmet> Zimmet { get; set; }
    }
}
