//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ZimmetTakipSistemi
{
    using System;
    using System.Collections.Generic;
    
    public partial class Zimmet
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Zimmet()
        {
            this.Atık = new HashSet<Atık>();
        }
    
        public int Zimmet_ıd { get; set; }
        public Nullable<int> Kullanıcı_ıd { get; set; }
        public Nullable<System.DateTime> Tarih { get; set; }
        public Nullable<int> Urun_ıd { get; set; }
        public Nullable<int> Adet { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Atık> Atık { get; set; }
        public virtual Kullanıcı Kullanıcı { get; set; }
        public virtual Urunler Urunler { get; set; }
    }
}
